image:
  repository: ghcr.io/hematoscope/job-template-run
  tag: 0.5.0
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

controller:
  cleanup_interval_minutes: 60
  cleanup_expiry_minutes: 1440
