image:
  repository: ghcr.io/hematoscope/job-template-run
  tag: 0.14.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

rbac:
  create: true
