image:
  repository: ghcr.io/cellbytes/job-template-run
  tag: 0.19.1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

timerInterval: 30.0
