apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobruns.hematoscope.app
  labels:
    app.kubernetes.io/name: {{ include "job-template-run.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  group: hematoscope.app
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                templateRef:
                  type: string
                command:
                  type: array
                  items:
                    type: string
                args:
                  type: array
                  items:
                    type: string

  scope: Namespaced
  names:
    plural: jobruns
    singular: jobrun
    kind: JobRun
    shortNames:
      - jr
