apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobtemplates.cellbytes.io
  labels:
    app.kubernetes.io/name: {{ include "job-template-run.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  group: cellbytes.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: Direct JobSpec
              x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: jobtemplates
    singular: jobtemplate
    kind: JobTemplate
    shortNames:
      - jt
