apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobtemplates.hematoscope.app
spec:
  group: hematoscope.app
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                template:
                  type: object
                  description: Direct JobTemplateSpec (spec.template of a Job)
  scope: Namespaced
  names:
    plural: jobtemplates
    singular: jobtemplate
    kind: JobTemplate
    shortNames:
      - jt
