apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobruns.hematoscope.app
spec:
  group: hematoscope.app
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                templateRef:
                  type: string
                command:
                  type: array
                  items:
                    type: string
                args:
                  type: array
                  items:
                    type: string
      additionalPrinterColumns:
        - name: Template
          type: string
          jsonPath: .spec.templateRef
          description: The referenced JobTemplate
        - name: Start Time
          type: date
          jsonPath: .status.startTime
          description: The time when the job started
        - name: Completion Time
          type: date
          jsonPath: .status.completionTime
          description: The time when the job completed
        - name: Status
          type: string
          jsonPath: .status.conditions[-1].type
          description: The current status of the job
  scope: Namespaced
  names:
    plural: jobruns
    singular: jobrun
    kind: JobRun
    shortNames:
      - jr
  