apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobruns.hematoscope.app
spec:
  group: hematoscope.app
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                templateRef:
                  type: string
                command:
                  type: array
                  items:
                    type: string
  scope: Namespaced
  names:
    plural: jobruns
    singular: jobrun
    kind: JobRun
    shortNames:
      - jr
