apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "job-template-run.fullname" . }}-controller
  labels:
    app.kubernetes.io/name: {{ include "job-template-run.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "job-template-run.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "job-template-run.name" . }}
        app.kubernetes.io/name: {{ include "job-template-run.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      serviceAccountName: {{ include "job-template-run.serviceAccountName" . }}
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "kopf"
            - "run"
            - "--liveness=http://0.0.0.0:8080/healthz"
            - "--standalone"
            - "--verbose"
            - "/app/controller.py"
          env:
            - name: APP_NAME
              value: {{ include "job-template-run.name" . }}
            - name: APP_INSTANCE
              value: {{ .Release.Name }}
            - name: APP_VERSION
              value: {{ .Chart.Version }}
            - name: APP_MANAGED_BY
              value: {{ .Release.Service }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
