{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "job-template-run.fullname" . }}-role
  labels:
    app.kubernetes.io/name: {{ include "job-template-run.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "patch", "get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list", "watch"]


  - apiGroups: ["hematoscope.app"]
    resources: ["jobruns"]
    verbs: ["list", "patch", "watch"]
  - apiGroups: ["hematoscope.app"]
    resources: ["jobtemplates"]
    verbs: ["get"]
{{- end }}
