{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "job-template-run.fullname" . }}-binding
  labels:
    app.kubernetes.io/name: {{ include "job-template-run.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "job-template-run.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "job-template-run.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
