name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Install Kyverno Chainsaw
        run: |
          curl -Lo chainsaw.tar.gz https://github.com/kyverno/chainsaw/releases/download/v0.2.12/chainsaw_linux_amd64.tar.gz
          tar -xzf chainsaw.tar.gz -C /usr/local/bin chainsaw
          chmod +x /usr/local/bin/chainsaw

      - name: Install KinD
        uses: helm/kind-action@v1.12.0
        with:
          version: v0.24.0
          install_only: true

      - name: Lint Helm chart
        run: make lint

      - name: Create KinD cluster
        run: make kind

      - name: Build and load Docker image into kind cluster
        run: make build

      - name: Deploy Helm chart
        run: make helm-install

      - name: Run tests
        run: make test
